public enum Country: String {
    case germany = "de"
    case unitedKingdom = "gb"
    case unitedStates = "us"
    case afghanistan = "af"
    case albania = "al"
    case algeria = "dz"
    case americanSamoa = "as"
    case andorra = "ad"
    case angola = "ao"
    case anguilla = "ai"
    case antarctica = "aq"
    case antiguaAndBarbuda = "ag"
    case argentina = "ar"
    case armenia = "am"
    case aruba = "aw"
    case australia = "au"
    case austria = "at"
    case azerbaijan = "az"
    case bahamas = "bs"
    case bahrain = "bh"
    case bangladesh = "bd"
    case barbados = "bb"
    case belarus = "by"
    case belgium = "be"
    case belize = "bz"
    case benin = "bj"
    case bermuda = "bm"
    case bhutan = "bt"
    case bolivia = "bo"
    case bosniaAndHerzegovina = "ba"
    case botswana = "bw"
    case bouvetIsland = "bv"
    case brazil = "br"
    case britishIndianOceanTerritory = "io"
    case bruneiDarussalam = "bn"
    case bulgaria = "bg"
    case burkinaFaso = "bf"
    case burundi = "bi"
    case cambodia = "kh"
    case cameroon = "cm"
    case canada = "ca"
    case capeVerde = "cv"
    case caymanIslands = "ky"
    case centralAfricanRepublic = "cf"
    case chad = "td"
    case chile = "cl"
    case china = "cn"
    case christmasIsland = "cx"
    case cocosKeelingIslands = "cc"
    case colombia = "co"
    case comoros = "km"
    case congo = "cg"
    case democraticRepublicOfTheCongo = "cd"
    case cookIslands = "ck"
    case costaRica = "cr"
    case coteDivoire = "ci"
    case croatia = "hr"
    case cuba = "cu"
    case cyprus = "cy"
    case czechRepublic = "cz"
    case denmark = "dk"
    case djibouti = "dj"
    case dominica = "dm"
    case dominicanRepublic = "do"
    case ecuador = "ec"
    case egypt = "eg"
    case elSalvador = "sv"
    case equatorialGuinea = "gq"
    case eritrea = "er"
    case estonia = "ee"
    case ethiopia = "et"
    case falklandIslandsMalvinas = "fk"
    case faroeIslands = "fo"
    case fiji = "fj"
    case finland = "fi"
    case france = "fr"
    case frenchGuiana = "gf"
    case frenchPolynesia = "pf"
    case frenchSouthernTerritories = "tf"
    case gabon = "ga"
    case gambia = "gm"
    case georgia = "ge"
    case ghana = "gh"
    case gibraltar = "gi"
    case greece = "gr"
    case greenland = "gl"
    case grenada = "gd"
    case guadeloupe = "gp"
    case guam = "gu"
    case guatemala = "gt"
    case guernsey = "gg"
    case guinea = "gn"
    case guineabissau = "gw"
    case guyana = "gy"
    case haiti = "ht"
    case heardIslandAndMcdonaldIslands = "hm"
    case holySeeVaticanCityState = "va"
    case honduras = "hn"
    case hongKong = "hk"
    case hungary = "hu"
    case iceland = "is"
    case india = "in"
    case indonesia = "id"
    case iran = "ir"
    case iraq = "iq"
    case ireland = "ie"
    case isleOfMan = "im"
    case israel = "il"
    case italy = "it"
    case jamaica = "jm"
    case japan = "jp"
    case jersey = "je"
    case jordan = "jo"
    case kazakhstan = "kz"
    case kenya = "ke"
    case kiribati = "ki"
    case northKorea = "kp"
    case southKorea = "kr"
    case kuwait = "kw"
    case kyrgyzstan = "kg"
    case laoPeoplesDemocraticRepublic = "la"
    case latvia = "lv"
    case lebanon = "lb"
    case lesotho = "ls"
    case liberia = "lr"
    case libyanArabJamahiriya = "ly"
    case liechtenstein = "li"
    case lithuania = "lt"
    case luxembourg = "lu"
    case macao = "mo"
    case macedonia = "mk"
    case madagascar = "mg"
    case malawi = "mw"
    case malaysia = "my"
    case maldives = "mv"
    case mali = "ml"
    case malta = "mt"
    case marshallIslands = "mh"
    case martinique = "mq"
    case mauritania = "mr"
    case mauritius = "mu"
    case mayotte = "yt"
    case mexico = "mx"
    case micronesia = "fm"
    case moldova = "md"
    case monaco = "mc"
    case mongolia = "mn"
    case montenegro = "me"
    case montserrat = "ms"
    case morocco = "ma"
    case mozambique = "mz"
    case myanmar = "mm"
    case namibia = "na"
    case nauru = "nr"
    case nepal = "np"
    case netherlands = "nl"
    case netherlandsAntilles = "an"
    case newCaledonia = "nc"
    case newZealand = "nz"
    case nicaragua = "ni"
    case niger = "ne"
    case nigeria = "ng"
    case niue = "nu"
    case norfolkIsland = "nf"
    case northernMarianaIslands = "mp"
    case norway = "no"
    case oman = "om"
    case pakistan = "pk"
    case palau = "pw"
    case palestinianTerritory = "NULL"
    case panama = "pa"
    case papuaNewGuinea = "pg"
    case paraguay = "py"
    case peru = "pe"
    case philippines = "ph"
    case pitcairn = "pn"
    case poland = "pl"
    case portugal = "pt"
    case puertoRico = "pr"
    case qatar = "qa"
    case reunion = "re"
    case romania = "ro"
    case russianFederation = "ru"
    case rwanda = "rw"
    case saintHelena = "sh"
    case saintKittsAndNevis = "kn"
    case saintLucia = "lc"
    case saintPierreAndMiquelon = "pm"
    case saintVincentAndTheGrenadines = "vc"
    case samoa = "ws"
    case sanMarino = "sm"
    case saoTomeAndPrincipe = "st"
    case saudiArabia = "sa"
    case senegal = "sn"
    case serbia = "rs"
    case seychelles = "sc"
    case sierraLeone = "sl"
    case singapore = "sg"
    case slovakia = "sk"
    case slovenia = "si"
    case solomonIslands = "sb"
    case somalia = "so"
    case southAfrica = "za"
    case southGeorgiaAndTheSouthSandwichIslands = "gs"
    case spain = "es"
    case sriLanka = "lk"
    case sudan = "sd"
    case suriname = "sr"
    case svalbardAndJanMayen = "sj"
    case swaziland = "sz"
    case sweden = "se"
    case switzerland = "ch"
    case syrianArabRepublic = "sy"
    case taiwan = "tw"
    case tajikistan = "tj"
    case tanzania = "tz"
    case thailand = "th"
    case timorleste = "tl"
    case togo = "tg"
    case tokelau = "tk"
    case tonga = "to"
    case trinidadAndTobago = "tt"
    case tunisia = "tn"
    case turkey = "tr"
    case turkmenistan = "tm"
    case turksAndCaicosIslands = "tc"
    case tuvalu = "tv"
    case uganda = "ug"
    case ukraine = "ua"
    case unitedArabEmirates = "ae"
    case unitedStatesMinorOutlyingIslands = "um"
    case uruguay = "uy"
    case uzbekistan = "uz"
    case vanuatu = "vu"
    case venezuela = "ve"
    case vietNam = "vn"
    case virginIslandsUK = "vg"
    case virginIslandsUS = "vi"
    case wallisAndFutuna = "wf"
    case westernSahara = "eh"
    case yemen = "ye"
    case zambia = "zm"
    case zimbabwe = "zw"
    
    case allCountries = "ac"
    
    public var abbreviation: String? {
        if self.rawValue == "NULL" {
            return nil
        } else {
            return self.rawValue
        }
    }
    
    public var name: String {
        switch self {
        case .germany: return "Germany"
        case .unitedKingdom: return "United Kingdom"
        case .unitedStates: return "United States"
        case .afghanistan: return "Afghanistan"
        case .albania: return "Albania"
        case .algeria: return "Algeria"
        case .americanSamoa: return "American Samoa"
        case .andorra: return "Andorra"
        case .angola: return "Angola"
        case .anguilla: return "Anguilla"
        case .antarctica: return "Antarctica"
        case .antiguaAndBarbuda: return "Antigua and Barbuda"
        case .argentina: return "Argentina"
        case .armenia: return "Armenia"
        case .aruba: return "Aruba"
        case .australia: return "Australia"
        case .austria: return "Austria"
        case .azerbaijan: return "Azerbaijan"
        case .bahamas: return "Bahamas"
        case .bahrain: return "Bahrain"
        case .bangladesh: return "Bangladesh"
        case .barbados: return "Barbados"
        case .belarus: return "Belarus"
        case .belgium: return "Belgium"
        case .belize: return "Belize"
        case .benin: return "Benin"
        case .bermuda: return "Bermuda"
        case .bhutan: return "Bhutan"
        case .bolivia: return "Bolivia"
        case .bosniaAndHerzegovina: return "Bosnia and Herzegovina"
        case .botswana: return "Botswana"
        case .bouvetIsland: return "Bouvet Island"
        case .brazil: return "Brazil"
        case .britishIndianOceanTerritory: return "British Indian Ocean Territory"
        case .bruneiDarussalam: return "Brunei Darussalam"
        case .bulgaria: return "Bulgaria"
        case .burkinaFaso: return "Burkina Faso"
        case .burundi: return "Burundi"
        case .cambodia: return "Cambodia"
        case .cameroon: return "Cameroon"
        case .canada: return "Canada"
        case .capeVerde: return "Cape Verde"
        case .caymanIslands: return "Cayman Islands"
        case .centralAfricanRepublic: return "Central African Republic"
        case .chad: return "Chad"
        case .chile: return "Chile"
        case .china: return "China"
        case .christmasIsland: return "Christmas Island"
        case .cocosKeelingIslands: return "Cocos (Keeling) Islands"
        case .colombia: return "Colombia"
        case .comoros: return "Comoros"
        case .congo: return "Congo"
        case .democraticRepublicOfTheCongo: return "Democratic Republic Of The Congo"
        case .cookIslands: return "Cook Islands"
        case .costaRica: return "Costa Rica"
        case .coteDivoire: return "Cote D'ivoire"
        case .croatia: return "Croatia"
        case .cuba: return "Cuba"
        case .cyprus: return "Cyprus"
        case .czechRepublic: return "Czech Republic"
        case .denmark: return "Denmark"
        case .djibouti: return "Djibouti"
        case .dominica: return "Dominica"
        case .dominicanRepublic: return "Dominican Republic"
        case .ecuador: return "Ecuador"
        case .egypt: return "Egypt"
        case .elSalvador: return "El Salvador"
        case .equatorialGuinea: return "Equatorial Guinea"
        case .eritrea: return "Eritrea"
        case .estonia: return "Estonia"
        case .ethiopia: return "Ethiopia"
        case .falklandIslandsMalvinas: return "Falkland Islands (Malvinas"
        case .faroeIslands: return "Faroe Islands"
        case .fiji: return "Fiji"
        case .finland: return "Finland"
        case .france: return "France"
        case .frenchGuiana: return "French Guiana"
        case .frenchPolynesia: return "French Polynesia"
        case .frenchSouthernTerritories: return "French Southern Territories"
        case .gabon: return "Gabon"
        case .gambia: return "Gambia"
        case .georgia: return "Georgia"
        case .ghana: return "Ghana"
        case .gibraltar: return "Gibraltar"
        case .greece: return "Greece"
        case .greenland: return "Greenland"
        case .grenada: return "Grenada"
        case .guadeloupe: return "Guadeloupe"
        case .guam: return "Guam"
        case .guatemala: return "Guatemala"
        case .guernsey: return "Guernsey"
        case .guinea: return "Guinea"
        case .guineabissau: return "Guineabissau"
        case .guyana: return "Guyana"
        case .haiti: return "Haiti"
        case .heardIslandAndMcdonaldIslands: return "Heard Island and Mcdonald Islands"
        case .holySeeVaticanCityState: return "Holy See (Vatican City State"
        case .honduras: return "Honduras"
        case .hongKong: return "Hong Kong"
        case .hungary: return "Hungary"
        case .iceland: return "Iceland"
        case .india: return "India"
        case .indonesia: return "Indonesia"
        case .iran: return "Iran"
        case .iraq: return "Iraq"
        case .ireland: return "Ireland"
        case .isleOfMan: return "Isle of Man"
        case .israel: return "Israel"
        case .italy: return "Italy"
        case .jamaica: return "Jamaica"
        case .japan: return "Japan"
        case .jersey: return "Jersey"
        case .jordan: return "Jordan"
        case .kazakhstan: return "Kazakhstan"
        case .kenya: return "Kenya"
        case .kiribati: return "Kiribati"
        case .northKorea: return "North Korea"
        case .southKorea: return "South Korea"
        case .kuwait: return "Kuwait"
        case .kyrgyzstan: return "Kyrgyzstan"
        case .laoPeoplesDemocraticRepublic: return "Lao People's Democratic Republic"
        case .latvia: return "Latvia"
        case .lebanon: return "Lebanon"
        case .lesotho: return "Lesotho"
        case .liberia: return "Liberia"
        case .libyanArabJamahiriya: return "Libyan Arab Jamahiriya"
        case .liechtenstein: return "Liechtenstein"
        case .lithuania: return "Lithuania"
        case .luxembourg: return "Luxembourg"
        case .macao: return "Macao"
        case .macedonia: return "Macedonia"
        case .madagascar: return "Madagascar"
        case .malawi: return "Malawi"
        case .malaysia: return "Malaysia"
        case .maldives: return "Maldives"
        case .mali: return "Mali"
        case .malta: return "Malta"
        case .marshallIslands: return "Marshall Islands"
        case .martinique: return "Martinique"
        case .mauritania: return "Mauritania"
        case .mauritius: return "Mauritius"
        case .mayotte: return "Mayotte"
        case .mexico: return "Mexico"
        case .micronesia: return "Micronesia"
        case .moldova: return "Moldova"
        case .monaco: return "Monaco"
        case .mongolia: return "Mongolia"
        case .montenegro: return "Montenegro"
        case .montserrat: return "Montserrat"
        case .morocco: return "Morocco"
        case .mozambique: return "Mozambique"
        case .myanmar: return "Myanmar"
        case .namibia: return "Namibia"
        case .nauru: return "Nauru"
        case .nepal: return "Nepal"
        case .netherlands: return "Netherlands"
        case .netherlandsAntilles: return "Netherlands Antilles"
        case .newCaledonia: return "New Caledonia"
        case .newZealand: return "New Zealand"
        case .nicaragua: return "Nicaragua"
        case .niger: return "Niger"
        case .nigeria: return "Nigeria"
        case .niue: return "Niue"
        case .norfolkIsland: return "Norfolk Island"
        case .northernMarianaIslands: return "Northern Mariana Islands"
        case .norway: return "Norway"
        case .oman: return "Oman"
        case .pakistan: return "Pakistan"
        case .palau: return "Palau"
        case .palestinianTerritory: return "Palestinian Territory"
        case .panama: return "Panama"
        case .papuaNewGuinea: return "Papua New Guinea"
        case .paraguay: return "Paraguay"
        case .peru: return "Peru"
        case .philippines: return "Philippines"
        case .pitcairn: return "Pitcairn"
        case .poland: return "Poland"
        case .portugal: return "Portugal"
        case .puertoRico: return "Puerto Rico"
        case .qatar: return "Qatar"
        case .reunion: return "Reunion"
        case .romania: return "Romania"
        case .russianFederation: return "Russian Federation"
        case .rwanda: return "Rwanda"
        case .saintHelena: return "Saint Helena"
        case .saintKittsAndNevis: return "Saint Kitts and Nevis"
        case .saintLucia: return "Saint Lucia"
        case .saintPierreAndMiquelon: return "Saint Pierre and Miquelon"
        case .saintVincentAndTheGrenadines: return "Saint Vincent and The Grenadines"
        case .samoa: return "Samoa"
        case .sanMarino: return "San Marino"
        case .saoTomeAndPrincipe: return "Sao Tome and Principe"
        case .saudiArabia: return "Saudi Arabia"
        case .senegal: return "Senegal"
        case .serbia: return "Serbia"
        case .seychelles: return "Seychelles"
        case .sierraLeone: return "Sierra Leone"
        case .singapore: return "Singapore"
        case .slovakia: return "Slovakia"
        case .slovenia: return "Slovenia"
        case .solomonIslands: return "Solomon Islands"
        case .somalia: return "Somalia"
        case .southAfrica: return "South Africa"
        case .southGeorgiaAndTheSouthSandwichIslands: return "South Georgia and The South Sandwich Islands"
        case .spain: return "Spain"
        case .sriLanka: return "Sri Lanka"
        case .sudan: return "Sudan"
        case .suriname: return "Suriname"
        case .svalbardAndJanMayen: return "Svalbard and Jan Mayen"
        case .swaziland: return "Swaziland"
        case .sweden: return "Sweden"
        case .switzerland: return "Switzerland"
        case .syrianArabRepublic: return "Syrian Arab Republic"
        case .taiwan: return "Taiwan"
        case .tajikistan: return "Tajikistan"
        case .tanzania: return "Tanzania"
        case .thailand: return "Thailand"
        case .timorleste: return "Timorleste"
        case .togo: return "Togo"
        case .tokelau: return "Tokelau"
        case .tonga: return "Tonga"
        case .trinidadAndTobago: return "Trinidad and Tobago"
        case .tunisia: return "Tunisia"
        case .turkey: return "Turkey"
        case .turkmenistan: return "Turkmenistan"
        case .turksAndCaicosIslands: return "Turks and Caicos Islands"
        case .tuvalu: return "Tuvalu"
        case .uganda: return "Uganda"
        case .ukraine: return "Ukraine"
        case .unitedArabEmirates: return "United Arab Emirates"
        case .unitedStatesMinorOutlyingIslands: return "United States Minor Outlying Islands"
        case .uruguay: return "Uruguay"
        case .uzbekistan: return "Uzbekistan"
        case .vanuatu: return "Vanuatu"
        case .venezuela: return "Venezuela"
        case .vietNam: return "Viet Nam"
        case .virginIslandsUK: return " British Virgin Islands"
        case .virginIslandsUS: return "United States Virgin Islands"
        case .wallisAndFutuna: return "Wallis and Futuna"
        case .westernSahara: return "Western Sahara"
        case .yemen: return "Yemen"
        case .zambia: return "Zambia"
        case .zimbabwe: return "Zimbabwe"
        case .allCountries: return "All Countries"
        }
    }
}
